package aprs

import "fmt"

type Symbol [2]byte

func (s Symbol) IsPrimaryTable() bool { return s[0] != '\\' }

func (s Symbol) String() string {
	var m map[byte]string
	if s.IsPrimaryTable() {
		m = primarySymbol
	} else {
		m = alternateSymbol
	}
	if n, ok := m[s[1]]; ok {
		return n
	}
	return fmt.Sprintf("unknown symbol %c", s[1])
}

func IsValidCompressedSymTable(c byte) bool {
	return c == '/' ||
		c == '\\' ||
		(c >= 0x41 && c <= 0x5a) ||
		(c >= 0x61 && c <= 0x6a)
}

func IsValidUncompressedSymTable(c byte) bool {
	return c == '/' ||
		c == '\\' ||
		(c >= 0x41 && c <= 0x5a) ||
		(c >= 0x30 && c <= 0x39)
}

// http://www.aprs.org/symbols/symbolsX.txt
var (
	primarySymbol = map[byte]string{
		'!':  "Police, Sheriff",
		'"':  "reserved",
		'#':  "Digi",
		'$':  "Phone",
		'%':  "DX Cluster",
		'&':  "HF Gateway",
		'\'': "Small Aircraft",
		'(':  "Mobile Satellite Station",
		')':  "Wheelchair",
		'*':  "Snowmobile",
		'+':  "Red Cross",
		',':  "Boy Scout",
		'-':  "House QTH (VHF)",
		'.':  "X",
		'/':  "Red Dot",
		'0':  "Circle (0)",
		'1':  "Circle (1)",
		'2':  "Circle (2)",
		'3':  "Circle (3)",
		'4':  "Circle (4)",
		'5':  "Circle (5)",
		'6':  "Circle (6)",
		'7':  "Circle (7)",
		'8':  "Circle (8)",
		'9':  "Circle (9)",
		':':  "Fire",
		';':  "Campground",
		'<':  "Motorcycle",
		'=':  "Railroad Engine",
		'>':  "Car",
		'?':  "File Server",
		'@':  "HC Future",
		'A':  "Aid Station",
		'B':  "BBS or PBBS",
		'C':  "Canoe",
		'D':  "",
		'E':  "Eyeball",
		'F':  "Tractor",
		'G':  "Grid Square",
		'H':  "Hotel",
		'I':  "TCP/IP",
		'J':  "",
		'K':  "School",
		'L':  "PC User",
		'M':  "MacAPRS",
		'N':  "NTS Station",
		'O':  "Balloon",
		'P':  "Police",
		'Q':  "",
		'R':  "Recreational Vehicle",
		'S':  "Shuttle",
		'T':  "SSTV",
		'U':  "Bus",
		'V':  "ATV",
		'W':  "National WX Service Site",
		'X':  "Helo",
		'Y':  "Yacht",
		'Z':  "WinAPRS",
		'[':  "Human/Person",
		'\\': "DF Station",
		']':  "Post Office",
		'^':  "Large Aircraft",
		'_':  "Weather Station",
		'`':  "Dish Antenna",
		'a':  "Ambulance",
		'b':  "Bike",
		'c':  "Incident Command Post",
		'd':  "Fire Dept",
		'e':  "Horse",
		'f':  "Fire Truck",
		'g':  "Glider",
		'h':  "Hospital",
		'i':  "IOTA",
		'j':  "Jeep",
		'k':  "Truck",
		'l':  "Laptop",
		'm':  "Mic-E Repeater",
		'n':  "Node",
		'o':  "EOC",
		'p':  "Dog",
		'q':  "Grid SQ",
		'r':  "Repeater",
		's':  "Power Boat",
		't':  "Truck Stop",
		'u':  "Truck (18 Wheeler)",
		'v':  "Van",
		'w':  "Water Station",
		'x':  "xAPRS",
		'y':  "Yagi @ QTH",
		'z':  "",
		'{':  "",
		'|':  "TNC Stream Switch",
		'}':  "",
		'~':  "TNC Stream Switch",
	}
	alternateSymbol = map[byte]string{
		'!':  "Emergency",
		'"':  "Reserved",
		'#':  "Overlay Digi",
		'$':  "Bank/ATM",
		'%':  "Power Plant",
		'&':  "I=Igte R=RX T=1hopTX 2=2hopTX",
		'\'': "Crash Site",
		'(':  "Cloudy",
		')':  "Firenet MEO",
		'*':  "",
		'+':  "Church",
		',':  "Girl Scouts",
		'-':  "House",
		'.':  "Ambiguous",
		'/':  "Waypoint Destination",
		'0':  "Circle",
		'1':  "",
		'2':  "",
		'3':  "",
		'4':  "",
		'5':  "",
		'6':  "",
		'7':  "",
		'8':  "WiFi Network",
		'9':  "Gas Station",
		':':  "",
		';':  "Park/Picnic",
		'<':  "Advisory",
		'=':  "",
		'>':  "Cars & Vehicles",
		'?':  "Info Kiosk",
		'@':  "Hurricane",
		'A':  "Box DTMF & RFID",
		'B':  "",
		'C':  "Coast Guard",
		'D':  "Depots",
		'E':  "Smoke",
		'F':  "",
		'G':  "",
		'H':  "Haze",
		'I':  "Rain Shower",
		'J':  "",
		'K':  "Kenwood HT",
		'L':  "Lighthouse",
		'M':  "MARS",
		'N':  "Navigation Buoy",
		'O':  "Rocket",
		'P':  "Parking",
		'Q':  "Quake",
		'R':  "Restaurant",
		'S':  "Satellite/Pacsat",
		'T':  "Thunderstorm",
		'U':  "Sunny",
		'V':  "VORTAC Nav Aid",
		'W':  "NWS Site",
		'X':  "Pharmacy",
		'Y':  "Radios and devices",
		'Z':  "",
		'[':  "W. Cloud",
		'\\': "GPS",
		']':  "",
		'^':  "Other Aircraft",
		'_':  "WX Site",
		'`':  "Rain",
		'a':  "",
		'b':  "",
		'c':  "CD Triangle",
		'd':  "DX Spot",
		'e':  "Sleet",
		'f':  "Funnel Cloud",
		'g':  "Gale Flags",
		'h':  "Store or Hamfest",
		'i':  "Box / POI",
		'j':  "Work Zone",
		'k':  "Special Vehicle",
		'l':  "Areas",
		'm':  "Value Sign",
		'n':  "Triangle",
		'o':  "Small Circle",
		'p':  "",
		'q':  "",
		'r':  "Restrooms",
		's':  "Ship/Boats",
		't':  "Tornado",
		'u':  "Truck",
		'v':  "Van",
		'w':  "Flooding",
		'x':  "Wreck/Obstruction",
		'y':  "Skywarn",
		'z':  "Shelter",
		'{':  "",
		'|':  "TNC Stream Switch",
		'}':  "",
		'~':  "TNC Stream Switch",
	}
)
